-- Generated by scripts/mock-data/generate-seed-sql.ts
-- Do not edit by hand. Run: npm run db:generate:seed
--
-- Fictional development data only. Every record is marked is_test true.
-- Contains no schema statements, no tickets, no check-ins and no users.

insert into public.graduation_events (id, event_code, event_name, starts_at, ends_at, timezone, venue_name, venue_address, status, is_test)
values
  ('00000000-0000-4000-8000-000000000001', 'GRAD-2026-DEV', 'Graduation Check-In Development Event', '2026-06-25T22:00:00.000Z', '2026-06-26T01:00:00.000Z', 'America/Toronto', 'Fictional Test Auditorium', '123 Example Street, Toronto, ON', 'draft', true)
on conflict (id) do update set
  event_code = excluded.event_code,
  event_name = excluded.event_name,
  starts_at = excluded.starts_at,
  ends_at = excluded.ends_at,
  timezone = excluded.timezone,
  venue_name = excluded.venue_name,
  venue_address = excluded.venue_address,
  status = excluded.status,
  is_test = excluded.is_test;

insert into public.graduation_registrations (id, event_id, registration_code, source_system, source_registration_id, graduate_full_name, email, phone, gown_size, name_pronunciation, registered_adult_guests, registered_children_0_4, registered_children_5_10, registration_status, payment_status, fee_total, tax_total, order_total, source_order_date, internal_notes, is_test)
values
  ('00000000-0000-4000-8000-000000000101', '00000000-0000-4000-8000-000000000001', 'REG-MOCK-001', 'mock', 'MOCK-001', 'Test Graduate 001', 'graduate001@example.com', '4165550101', 'M', null, 0.00, 0.00, 0.00, 'eligible', 'unknown', null, null, null, '2026-05-01T12:00:00.000Z', 'Scenario 01: graduate attending alone.', true),
  ('00000000-0000-4000-8000-000000000102', '00000000-0000-4000-8000-000000000001', 'REG-MOCK-002', 'mock', 'MOCK-002', 'Test Graduate 002', 'graduate002@example.com', '4165550102', 'L', null, 1.00, 0.00, 0.00, 'eligible', 'unknown', null, null, null, '2026-05-02T12:00:00.000Z', 'Scenario 02: one adult guest.', true),
  ('00000000-0000-4000-8000-000000000103', '00000000-0000-4000-8000-000000000001', 'REG-MOCK-003', 'mock', 'MOCK-003', 'Test Graduate 003', 'graduate003@example.com', '4165550103', 'S', null, 2.00, 0.00, 0.00, 'eligible', 'unknown', null, null, null, '2026-05-03T12:00:00.000Z', 'Scenario 03: two adult guests.', true),
  ('00000000-0000-4000-8000-000000000104', '00000000-0000-4000-8000-000000000001', 'REG-MOCK-004', 'mock', 'MOCK-004', 'Test Graduate 004', 'graduate004@example.com', '4165550104', 'M', null, 0.00, 1.00, 0.00, 'eligible', 'unknown', null, null, null, '2026-05-04T12:00:00.000Z', 'Scenario 04: one child aged 0 to 4.', true),
  ('00000000-0000-4000-8000-000000000105', '00000000-0000-4000-8000-000000000001', 'REG-MOCK-005', 'mock', 'MOCK-005', 'Test Graduate 005', 'graduate005@example.com', '4165550105', 'XL', null, 0.00, 2.00, 0.00, 'eligible', 'unknown', null, null, null, '2026-05-05T12:00:00.000Z', 'Scenario 05: two children aged 0 to 4.', true),
  ('00000000-0000-4000-8000-000000000106', '00000000-0000-4000-8000-000000000001', 'REG-MOCK-006', 'mock', 'MOCK-006', 'Test Graduate 006', 'graduate006@example.com', '4165550106', 'M', null, 0.00, 0.00, 1.00, 'eligible', 'unknown', null, null, null, '2026-05-06T12:00:00.000Z', 'Scenario 06: one child aged 5 to 10.', true),
  ('00000000-0000-4000-8000-000000000107', '00000000-0000-4000-8000-000000000001', 'REG-MOCK-007', 'mock', 'MOCK-007', 'Test Graduate 007', 'graduate007@example.com', '4165550107', 'L', null, 0.00, 0.00, 2.00, 'eligible', 'unknown', null, null, null, '2026-05-07T12:00:00.000Z', 'Scenario 07: two children aged 5 to 10.', true),
  ('00000000-0000-4000-8000-000000000108', '00000000-0000-4000-8000-000000000001', 'REG-MOCK-008', 'mock', 'MOCK-008', 'Test Graduate 008', 'graduate008@example.com', '4165550108', 'S', null, 0.00, 1.00, 1.00, 'eligible', 'unknown', null, null, null, '2026-05-08T12:00:00.000Z', 'Scenario 08: one child in each age group.', true),
  ('00000000-0000-4000-8000-000000000109', '00000000-0000-4000-8000-000000000001', 'REG-MOCK-009', 'mock', 'MOCK-009', 'Test Graduate 009', 'graduate009@example.com', '4165550109', 'M', null, 1.00, 0.00, 1.00, 'eligible', 'unknown', null, null, null, '2026-05-09T12:00:00.000Z', 'Scenario 09: one adult guest and one child.', true),
  ('00000000-0000-4000-8000-000000000110', '00000000-0000-4000-8000-000000000001', 'REG-MOCK-010', 'mock', 'MOCK-010', 'Test Graduate 010', 'graduate010@example.com', '4165550110', 'L', null, 2.00, 1.00, 1.00, 'eligible', 'unknown', null, null, null, '2026-05-10T12:00:00.000Z', 'Scenario 10: two adult guests and two children.', true),
  ('00000000-0000-4000-8000-000000000111', '00000000-0000-4000-8000-000000000001', 'REG-MOCK-011', 'mock', 'MOCK-011', 'Test Graduate 011', 'graduate011@example.com', '4165550111', 'M', null, 1.00, 0.00, 0.00, 'eligible', 'unknown', null, null, null, '2026-05-11T12:00:00.000Z', 'Scenario 11: payment status unknown.', true),
  ('00000000-0000-4000-8000-000000000112', '00000000-0000-4000-8000-000000000001', 'REG-MOCK-012', 'mock', 'MOCK-012', 'Test Graduate 012', 'graduate012@example.com', '4165550112', 'L', null, 2.00, 0.00, 0.00, 'eligible', 'amount_recorded', 75.00, 9.75, 84.75, '2026-05-12T12:00:00.000Z', 'Scenario 12: amount recorded from the source system.', true),
  ('00000000-0000-4000-8000-000000000113', '00000000-0000-4000-8000-000000000001', 'REG-MOCK-013', 'mock', 'MOCK-013', 'Test Graduate 013', 'graduate013@example.com', '4165550113', 'S', null, 1.00, 1.00, 0.00, 'eligible', 'pending', 50.00, 6.50, 56.50, '2026-05-13T12:00:00.000Z', 'Scenario 13: payment pending.', true),
  ('00000000-0000-4000-8000-000000000114', '00000000-0000-4000-8000-000000000001', 'REG-MOCK-014', 'mock', 'MOCK-014', 'Test Graduate 014', 'graduate014@example.com', '4165550114', 'M', null, 2.00, 0.00, 1.00, 'eligible', 'paid', 50.00, 6.50, 56.50, '2026-05-14T12:00:00.000Z', 'Scenario 14: payment paid.', true),
  ('00000000-0000-4000-8000-000000000115', '00000000-0000-4000-8000-000000000001', 'REG-MOCK-015', 'mock', 'MOCK-015', 'Test Graduate 015', 'graduate015@example.com', '4165550115', 'XL', null, 1.00, 0.00, 0.00, 'review_required', 'unknown', null, null, null, '2026-05-15T12:00:00.000Z', 'Scenario 15: registration requiring review.', true),
  ('00000000-0000-4000-8000-000000000116', '00000000-0000-4000-8000-000000000001', 'REG-MOCK-016', 'mock', 'MOCK-016', 'Test Graduate 016', 'graduate016@example.com', '4165550116', 'M', null, 0.00, 0.00, 0.00, 'failed', 'failed', 50.00, 6.50, 56.50, '2026-05-16T12:00:00.000Z', 'Scenario 16: failed registration.', true),
  ('00000000-0000-4000-8000-000000000117', '00000000-0000-4000-8000-000000000001', 'REG-MOCK-017', 'mock', 'MOCK-017', 'Test Graduate 017', 'graduate017@example.com', '4165550117', 'L', null, 1.00, 0.00, 0.00, 'cancelled', 'refunded', 50.00, 6.50, 56.50, '2026-05-17T12:00:00.000Z', 'Scenario 17: cancelled registration.', true),
  ('00000000-0000-4000-8000-000000000118', '00000000-0000-4000-8000-000000000001', 'REG-MOCK-018', 'mock', 'MOCK-018', 'Test Graduate 018', 'graduate018@example.com', '4165550118', null, null, 2.00, 0.00, 0.00, 'eligible', 'unknown', null, null, null, '2026-05-18T12:00:00.000Z', 'Scenario 18: missing gown size.', true),
  ('00000000-0000-4000-8000-000000000119', '00000000-0000-4000-8000-000000000001', 'REG-MOCK-019', 'mock', 'MOCK-019', 'Test Graduate 019', 'shared.family@example.com', '4165550119', 'M', 'TEST grad-yoo-it nine-teen', 1.00, 0.00, 1.00, 'eligible', 'unknown', null, null, null, '2026-05-19T12:00:00.000Z', 'Scenario 19: name pronunciation provided.', true),
  ('00000000-0000-4000-8000-000000000120', '00000000-0000-4000-8000-000000000001', 'REG-MOCK-020', 'mock', 'MOCK-020', 'Test Graduate 020', 'shared.family@example.com', '4165550120', 'S', null, 1.00, 1.00, 0.00, 'eligible', 'unknown', null, null, null, '2026-05-20T12:00:00.000Z', 'Scenario 20: shared fictional contact email for duplicate review.', true)
on conflict (id) do update set
  event_id = excluded.event_id,
  registration_code = excluded.registration_code,
  source_system = excluded.source_system,
  source_registration_id = excluded.source_registration_id,
  graduate_full_name = excluded.graduate_full_name,
  email = excluded.email,
  phone = excluded.phone,
  gown_size = excluded.gown_size,
  name_pronunciation = excluded.name_pronunciation,
  registered_adult_guests = excluded.registered_adult_guests,
  registered_children_0_4 = excluded.registered_children_0_4,
  registered_children_5_10 = excluded.registered_children_5_10,
  registration_status = excluded.registration_status,
  payment_status = excluded.payment_status,
  fee_total = excluded.fee_total,
  tax_total = excluded.tax_total,
  order_total = excluded.order_total,
  source_order_date = excluded.source_order_date,
  internal_notes = excluded.internal_notes,
  is_test = excluded.is_test;

insert into public.registration_guests (id, registration_id, guest_category, guest_name, sort_order, is_test)
values
  ('00000000-0000-4000-8000-000000000201', '00000000-0000-4000-8000-000000000102', 'adult', 'Test Adult Guest 002-1', 1.00, true),
  ('00000000-0000-4000-8000-000000000202', '00000000-0000-4000-8000-000000000103', 'adult', 'Test Adult Guest 003-1', 1.00, true),
  ('00000000-0000-4000-8000-000000000203', '00000000-0000-4000-8000-000000000103', 'adult', 'Test Adult Guest 003-2', 2.00, true),
  ('00000000-0000-4000-8000-000000000204', '00000000-0000-4000-8000-000000000104', 'child_0_4', null, 1.00, true),
  ('00000000-0000-4000-8000-000000000205', '00000000-0000-4000-8000-000000000105', 'child_0_4', null, 1.00, true),
  ('00000000-0000-4000-8000-000000000206', '00000000-0000-4000-8000-000000000105', 'child_0_4', null, 2.00, true),
  ('00000000-0000-4000-8000-000000000207', '00000000-0000-4000-8000-000000000106', 'child_5_10', 'Test Child Guest 006-1', 1.00, true),
  ('00000000-0000-4000-8000-000000000208', '00000000-0000-4000-8000-000000000107', 'child_5_10', 'Test Child Guest 007-1', 1.00, true),
  ('00000000-0000-4000-8000-000000000209', '00000000-0000-4000-8000-000000000107', 'child_5_10', 'Test Child Guest 007-2', 2.00, true),
  ('00000000-0000-4000-8000-000000000210', '00000000-0000-4000-8000-000000000108', 'child_0_4', null, 1.00, true),
  ('00000000-0000-4000-8000-000000000211', '00000000-0000-4000-8000-000000000108', 'child_5_10', 'Test Child Guest 008-1', 1.00, true),
  ('00000000-0000-4000-8000-000000000212', '00000000-0000-4000-8000-000000000109', 'adult', 'Test Adult Guest 009-1', 1.00, true),
  ('00000000-0000-4000-8000-000000000213', '00000000-0000-4000-8000-000000000109', 'child_5_10', 'Test Child Guest 009-1', 1.00, true),
  ('00000000-0000-4000-8000-000000000214', '00000000-0000-4000-8000-000000000110', 'adult', 'Test Adult Guest 010-1', 1.00, true),
  ('00000000-0000-4000-8000-000000000215', '00000000-0000-4000-8000-000000000110', 'adult', 'Test Adult Guest 010-2', 2.00, true),
  ('00000000-0000-4000-8000-000000000216', '00000000-0000-4000-8000-000000000110', 'child_0_4', null, 1.00, true),
  ('00000000-0000-4000-8000-000000000217', '00000000-0000-4000-8000-000000000110', 'child_5_10', 'Test Child Guest 010-1', 1.00, true),
  ('00000000-0000-4000-8000-000000000218', '00000000-0000-4000-8000-000000000111', 'adult', 'Test Adult Guest 011-1', 1.00, true),
  ('00000000-0000-4000-8000-000000000219', '00000000-0000-4000-8000-000000000112', 'adult', 'Test Adult Guest 012-1', 1.00, true),
  ('00000000-0000-4000-8000-000000000220', '00000000-0000-4000-8000-000000000112', 'adult', 'Test Adult Guest 012-2', 2.00, true),
  ('00000000-0000-4000-8000-000000000221', '00000000-0000-4000-8000-000000000113', 'adult', 'Test Adult Guest 013-1', 1.00, true),
  ('00000000-0000-4000-8000-000000000222', '00000000-0000-4000-8000-000000000113', 'child_0_4', null, 1.00, true),
  ('00000000-0000-4000-8000-000000000223', '00000000-0000-4000-8000-000000000114', 'adult', 'Test Adult Guest 014-1', 1.00, true),
  ('00000000-0000-4000-8000-000000000224', '00000000-0000-4000-8000-000000000114', 'adult', 'Test Adult Guest 014-2', 2.00, true),
  ('00000000-0000-4000-8000-000000000225', '00000000-0000-4000-8000-000000000114', 'child_5_10', 'Test Child Guest 014-1', 1.00, true),
  ('00000000-0000-4000-8000-000000000226', '00000000-0000-4000-8000-000000000115', 'adult', 'Test Adult Guest 015-1', 1.00, true),
  ('00000000-0000-4000-8000-000000000227', '00000000-0000-4000-8000-000000000117', 'adult', 'Test Adult Guest 017-1', 1.00, true),
  ('00000000-0000-4000-8000-000000000228', '00000000-0000-4000-8000-000000000118', 'adult', 'Test Adult Guest 018-1', 1.00, true),
  ('00000000-0000-4000-8000-000000000229', '00000000-0000-4000-8000-000000000118', 'adult', 'Test Adult Guest 018-2', 2.00, true),
  ('00000000-0000-4000-8000-000000000230', '00000000-0000-4000-8000-000000000119', 'adult', 'Test Adult Guest 019-1', 1.00, true),
  ('00000000-0000-4000-8000-000000000231', '00000000-0000-4000-8000-000000000119', 'child_5_10', 'Test Child Guest 019-1', 1.00, true),
  ('00000000-0000-4000-8000-000000000232', '00000000-0000-4000-8000-000000000120', 'adult', 'Test Adult Guest 020-1', 1.00, true),
  ('00000000-0000-4000-8000-000000000233', '00000000-0000-4000-8000-000000000120', 'child_0_4', null, 1.00, true)
on conflict (id) do update set
  registration_id = excluded.registration_id,
  guest_category = excluded.guest_category,
  guest_name = excluded.guest_name,
  sort_order = excluded.sort_order,
  is_test = excluded.is_test;
