/**
 * Deterministic source fingerprint for stale-document detection.
 *
 * The fingerprint is a SHA-256 over every input that affects the rendered
 * PDF. When a registration, an event detail or the ticket settings change,
 * the recomputed fingerprint stops matching the stored one and the
 * administrator sees that a new PDF is required.
 *
 * Determinism rules:
 *  - No clock value, random value or request-scoped value is ever mixed in.
 *    The same inputs must always produce the same fingerprint, on every
 *    machine and in any order of evaluation.
 *  - Keys are emitted in a fixed order and values are normalized, so
 *    incidental whitespace or key ordering never causes a false mismatch.
 *  - The ticket identity is included, so a replacement ticket never matches
 *    the document generated for the ticket it replaced.
 *
 * The fingerprint never includes a raw QR token, a token hash or a secret.
 * The QR image is a pure function of the ticket identity, which is already
 * covered by ticketId.
 */

import { createHash } from "node:crypto";
import type {
  ProgramScheduleEntry,
  RegisteredParty,
  TicketEventDetails,
} from "./types";

export interface FingerprintInput {
  ticketId: string;
  ticketStatus: string;
  ticketCode: string;
  party: RegisteredParty;
  event: TicketEventDetails;
  settings: {
    displayTitle: string;
    description: string;
    programSchedule: readonly ProgramScheduleEntry[];
    primaryLogoAsset: string;
    secondaryAsset: string | null;
    instructions: string | null;
  };
  templateVersion: number;
}

function norm(value: string | null | undefined): string {
  return (value ?? "").replace(/\s+/g, " ").trim();
}

/**
 * Builds the canonical string that is hashed. Kept separate from the hash
 * so tests can assert exactly which inputs participate.
 */
export function buildFingerprintPayload(input: FingerprintInput): string {
  const parts: string[] = [
    `template:${input.templateVersion}`,
    `ticket:${norm(input.ticketId).toLowerCase()}`,
    `ticket_status:${norm(input.ticketStatus)}`,
    `ticket_code:${norm(input.ticketCode).toUpperCase()}`,
    `graduate:${norm(input.party.graduateName)}`,
    `graduate_count:${input.party.graduateCount}`,
    `adult_count:${input.party.adultGuestCount}`,
    // Guest names participate in their displayed order, so reordering the
    // printed names is itself a change that requires a new PDF.
    `adult_names:${input.party.adultGuestNames.map(norm).join("|")}`,
    `child_0_4:${input.party.children04Count}`,
    `child_5_10:${input.party.children510Count}`,
    `party_total:${input.party.totalPartyCount}`,
    `event_title:${norm(input.event.title)}`,
    `event_date:${norm(input.event.dateLabel)}`,
    `event_start:${norm(input.event.startLabel)}`,
    `event_end:${norm(input.event.endLabel)}`,
    `event_tz:${norm(input.event.timezone)}`,
    `venue:${norm(input.event.venueName)}`,
    `address:${norm(input.event.venueAddress)}`,
    `settings_title:${norm(input.settings.displayTitle)}`,
    `settings_description:${norm(input.settings.description)}`,
    `schedule:${input.settings.programSchedule
      .map(
        (entry) =>
          `${norm(entry.startTime)}~${norm(entry.endTime)}~${norm(entry.title)}`
      )
      .join("|")}`,
    `logo:${norm(input.settings.primaryLogoAsset)}`,
    `secondary:${norm(input.settings.secondaryAsset)}`,
    `instructions:${norm(input.settings.instructions)}`,
  ];
  return parts.join("\n");
}

/** 64 lowercase hexadecimal characters. */
export function buildSourceFingerprint(input: FingerprintInput): string {
  return createHash("sha256")
    .update(buildFingerprintPayload(input), "utf8")
    .digest("hex");
}

/** SHA-256 of generated bytes, used to checksum every stored PDF. */
export function sha256Hex(bytes: Uint8Array): string {
  return createHash("sha256").update(bytes).digest("hex");
}

/** Short, display-safe form of a checksum for administrator screens. */
export function shortChecksum(checksum: string): string {
  return checksum.slice(0, 12);
}
