/**
 * Export manifest CSV.
 *
 * The manifest is consumed by a spreadsheet and, in the deferred
 * CHECKIN-09B work, by Google Apps Script. It therefore has to be safe to
 * open in Excel, Numbers and Google Sheets.
 *
 * Two separate protections apply to every value:
 *
 *  1. CSV quoting, so a value containing a comma, quote or newline cannot
 *     break out of its field.
 *  2. Formula-injection neutralization, so a value beginning with =, +, -
 *     or @ is never evaluated as a formula by the spreadsheet.
 *
 * The manifest deliberately excludes the raw QR token, the ticket-signing
 * secret, the service-role key, storage object URLs and internal
 * authentication user IDs.
 */

import { createHash } from "node:crypto";

import type { ExportManifestRow } from "./types";

/** Column order of the generated manifest. */
export const MANIFEST_COLUMNS = [
  "batch_code",
  "export_item_id",
  "event_title",
  "graduate_name",
  "recipient_email",
  "ticket_code",
  "document_version",
  "pdf_file_name",
  "pdf_sha256",
  "graduate_count",
  "adult_guest_count",
  "adult_guest_names",
  "child_0_4_count",
  "child_5_10_count",
  "total_party_count",
  "document_generated_at",
  "batch_created_at",
  "export_purpose",
  "item_status",
] as const;

/** Characters that make a spreadsheet treat a cell as a formula. */
const FORMULA_PREFIXES = ["=", "+", "-", "@"] as const;

/**
 * Neutralizes a value that a spreadsheet would otherwise evaluate.
 *
 * A leading single quote is the conventional, human-readable way to force
 * a cell to be treated as text. Tab and carriage return are also stripped
 * from the front because some spreadsheets skip them and then evaluate the
 * formula character that follows.
 */
export function neutralizeFormula(value: string): string {
  const stripped = value.replace(/^[\t\r\n]+/, "");
  if (stripped.length === 0) {
    return stripped;
  }
  const first = stripped.charAt(0);
  if ((FORMULA_PREFIXES as readonly string[]).includes(first)) {
    return `'${stripped}`;
  }
  return stripped;
}

/** Quotes a value for CSV, after neutralizing formula characters. */
export function csvCell(value: string): string {
  const safe = neutralizeFormula(value);
  return `"${safe.replace(/"/g, '""')}"`;
}

export function csvRow(values: readonly string[]): string {
  return values.map(csvCell).join(",");
}

function manifestValues(row: ExportManifestRow): string[] {
  return [
    row.batchCode,
    row.exportItemId,
    row.eventTitle,
    row.graduateName,
    row.recipientEmail,
    row.ticketCode,
    row.documentVersion,
    row.pdfFileName,
    row.pdfSha256,
    row.graduateCount,
    row.adultGuestCount,
    row.adultGuestNames,
    row.child04Count,
    row.child510Count,
    row.totalPartyCount,
    row.documentGeneratedAt,
    row.batchCreatedAt,
    row.exportPurpose,
    row.itemStatus,
  ];
}

/**
 * Builds the manifest CSV. Uses CRLF line endings, which every spreadsheet
 * reads correctly and which RFC 4180 specifies.
 */
export function buildManifestCsv(rows: readonly ExportManifestRow[]): string {
  const lines = [csvRow(MANIFEST_COLUMNS), ...rows.map((row) => csvRow(manifestValues(row)))];
  return `${lines.join("\r\n")}\r\n`;
}

export function manifestChecksum(csv: string): string {
  return createHash("sha256").update(csv, "utf8").digest("hex");
}

export interface BatchSummaryInput {
  batchCode: string;
  eventTitle: string;
  purpose: string;
  createdAt: string;
  exportedAt: string;
  itemCount: number;
  pdfCount: number;
  excludedCount: number;
  failedCount: number;
  manifestSha256: string;
  generatedByRole: string;
}

/**
 * Human-readable summary shipped inside the ZIP. Carries no secret: no raw
 * token, no signing secret, no service-role key and no storage URL.
 */
export function buildBatchSummary(input: BatchSummaryInput): string {
  return [
    "Toronto Academy of Education",
    "Convocation Ceremony 2026 - ticket document export batch",
    "",
    `Batch code:          ${input.batchCode}`,
    `Event:               ${input.eventTitle}`,
    `Purpose:             ${input.purpose}`,
    `Created:             ${input.createdAt}`,
    `Exported:            ${input.exportedAt}`,
    `Items:               ${input.itemCount}`,
    `PDF documents:       ${input.pdfCount}`,
    `Excluded:            ${input.excludedCount}`,
    `Failed:              ${input.failedCount}`,
    `Manifest SHA-256:    ${input.manifestSha256}`,
    `Generated by role:   ${input.generatedByRole}`,
    "",
    "This batch was prepared but NOT emailed by CHECKIN-09A.",
    "Distribution is handled separately by CHECKIN-09B.",
    "",
  ].join("\r\n");
}
