/**
 * Generates supabase/seed.sql from the fictional fixtures.
 *
 * The output is deterministic: running the generator twice without fixture
 * changes produces identical SQL. The file contains data statements only.
 * It must never contain schema creation, tickets, check-ins, Auth users,
 * real personal information or secrets.
 */

import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

import { mockEvent, mockGuests, mockRegistrations } from "./fixtures";

function sqlText(value: string): string {
  return `'${value.replace(/'/g, "''")}'`;
}

function sqlValue(value: string | number | boolean | null): string {
  if (value === null) {
    return "null";
  }
  if (typeof value === "boolean") {
    return value ? "true" : "false";
  }
  if (typeof value === "number") {
    if (!Number.isFinite(value)) {
      throw new Error("Seed values must be finite numbers.");
    }
    return value.toFixed(2);
  }
  return sqlText(value);
}

function insertStatement(
  table: string,
  columns: string[],
  rows: ReadonlyArray<ReadonlyArray<string | number | boolean | null>>,
  conflictTarget: string
): string {
  const updates = columns
    .filter((column) => column !== "id")
    .map((column) => `  ${column} = excluded.${column}`)
    .join(",\n");
  const valueLines = rows
    .map((row) => `  (${row.map(sqlValue).join(", ")})`)
    .join(",\n");

  return [
    `insert into ${table} (${columns.join(", ")})`,
    "values",
    valueLines,
    `on conflict (${conflictTarget}) do update set`,
    `${updates};`,
  ].join("\n");
}

export function buildSeedSql(): string {
  const header = [
    "-- Generated by scripts/mock-data/generate-seed-sql.ts",
    "-- Do not edit by hand. Run: npm run db:generate:seed",
    "--",
    "-- Fictional development data only. Every record is marked is_test true.",
    "-- Contains no schema statements, no tickets, no check-ins and no users.",
    "",
  ].join("\n");

  const eventSql = insertStatement(
    "public.graduation_events",
    [
      "id",
      "event_code",
      "event_name",
      "starts_at",
      "ends_at",
      "timezone",
      "venue_name",
      "venue_address",
      "status",
      "is_test",
    ],
    [
      [
        mockEvent.id,
        mockEvent.event_code,
        mockEvent.event_name,
        mockEvent.starts_at,
        mockEvent.ends_at,
        mockEvent.timezone,
        mockEvent.venue_name,
        mockEvent.venue_address,
        mockEvent.status,
        mockEvent.is_test,
      ],
    ],
    "id"
  );

  const registrationSql = insertStatement(
    "public.graduation_registrations",
    [
      "id",
      "event_id",
      "registration_code",
      "source_system",
      "source_registration_id",
      "graduate_full_name",
      "email",
      "phone",
      "gown_size",
      "name_pronunciation",
      "registered_adult_guests",
      "registered_children_0_4",
      "registered_children_5_10",
      "registration_status",
      "payment_status",
      "fee_total",
      "tax_total",
      "order_total",
      "source_order_date",
      "internal_notes",
      "is_test",
    ],
    mockRegistrations.map((registration) => [
      registration.id,
      registration.event_id,
      registration.registration_code,
      registration.source_system,
      registration.source_registration_id,
      registration.graduate_full_name,
      registration.email,
      registration.phone,
      registration.gown_size,
      registration.name_pronunciation,
      registration.registered_adult_guests,
      registration.registered_children_0_4,
      registration.registered_children_5_10,
      registration.registration_status,
      registration.payment_status,
      registration.fee_total,
      registration.tax_total,
      registration.order_total,
      registration.source_order_date,
      registration.internal_notes,
      registration.is_test,
    ]),
    "id"
  );

  const guestSql = insertStatement(
    "public.registration_guests",
    [
      "id",
      "registration_id",
      "guest_category",
      "guest_name",
      "sort_order",
      "is_test",
    ],
    mockGuests.map((guest) => [
      guest.id,
      guest.registration_id,
      guest.guest_category,
      guest.guest_name,
      guest.sort_order,
      guest.is_test,
    ]),
    "id"
  );

  return [header, eventSql, "", registrationSql, "", guestSql, ""].join("\n");
}

export function writeSeedSql(): { outputPath: string; bytes: number } {
  const scriptDir = dirname(fileURLToPath(import.meta.url));
  const outputPath = join(scriptDir, "..", "..", "supabase", "seed.sql");
  const sql = buildSeedSql();
  mkdirSync(dirname(outputPath), { recursive: true });
  writeFileSync(outputPath, sql, "utf8");
  return { outputPath, bytes: Buffer.byteLength(sql, "utf8") };
}

const isMain =
  typeof process.argv[1] === "string" &&
  import.meta.url === pathToFileURL(process.argv[1]).href;

if (isMain) {
  const { bytes } = writeSeedSql();
  console.log(
    `Seed SQL generated: 1 event, ${mockRegistrations.length} registrations, ` +
      `${mockGuests.length} guests (${bytes} bytes written to supabase/seed.sql).`
  );
}
